export const icons = (theme: string) => ({
    arrowLeft: theme === 'light'? require("../assets/arrowleft.svg"): require('../assets/arrowleft.svg'),
    bookMark: theme === 'light'? require("../assets/checked-bookmark.svg"): require('../assets/checked-bookmark.svg'),
    flowerIcon: theme === 'light'? require("../assets/flower-icon.png"): require('../assets/flower-icon.png'),
    hamburgurIcon: theme === 'light'? require("../assets/hamburgur-icon.svg"): require('../assets/hamburgur-icon.svg'),
    playIcon: theme === 'light'? require("../assets/play-icon.svg"): require('../assets/play-icon.svg'),
    krishnaBg: theme === 'light'? require("../assets/shri-krisna-bg.png"): require('../assets/shri-krisna-bg.png'),
    uncheckedBookmark: theme === 'light'? require("../assets/unchecked-bookmark.svg"): require('../assets/unchecked-bookmark.svg'),
    verseOfTheDay: require('../assets/verse-of-the-day.png'),
    cog: require("../assets/cog.svg"),
    list: require("../assets/list.svg"),
    chevronRight: require("../assets/chevron-right.svg"),
    language: require("../assets/language.png"),
    commentary: require("../assets/commentary.png"),
    wordMeaning: require("../assets/word-meaning.png"),
    translations: require("../assets/translations.png"),
    transliterations: require("../assets/transliteration.png"),
    author: require("../assets/author.png"),
})